language: node_js
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_f4dac5b284ce_key -iv $encrypted_f4dac5b284ce_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/id_rsa
before_script:
- npm install -g gulp
- npm install -g uglify-js
script: 
- gulp
- bash deploy

