language: node_js
node_js:
- '4.1'
before_install:
- openssl aes-256-cbc -K $encrypted_7b72a74a59ba_key -iv $encrypted_7b72a74a59ba_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/id_rsa
before_script:
- npm install -g gulp
- npm install -g uglifyjs
script: gulp

